In [1]:
import os
from PIL import Image
import numpy as np


# Set the directory you want to start from
Mydir = 'photos'
for dirName, subdirList, fileList in os.walk(Mydir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)

Found directory: photos
	1.jpg
	2.jpg
	abc.jpg
	airplane.jpg
	download (1).jpg
	download (2).jpg
	download.jpg
	images (1).jpg
	images (10).jpg
	images (11).jpg
	images (12).jpg
	images (13).jpg
	images (2).jpg
	images (3).jpg
	images (4).jpg
	images (5).jpg
	images (6).jpg
	images (7).jpg
	images (8).jpg
	images (9).jpg
	images.jpg
	Thumbs.db
	tinted.jpg


In [2]:
main_list = []
im = Image.open(dirName+"\\"+fileList[0])
print("----------X------------X-----------------------X\n\n")
im.show()
original_array = np.array(im)
print(original_array.shape)
print(original_array.size)
print(original_array)
print("\n\n----------X------------X-----------------------X\n\n")
new_image = im.resize((200, 200))
resized_array = np.array(new_image)
print(resized_array.size)
print(resized_array.shape)
print(resized_array)
main_list.append(resized_array)

----------X------------X-----------------------X


(480, 720, 3)
1036800
[[[ 63  68  74]
  [ 65  70  76]
  [ 67  72  78]
  ...
  [ 97 108 112]
  [ 96 107 111]
  [ 95 106 110]]

 [[ 64  69  75]
  [ 66  71  77]
  [ 67  72  78]
  ...
  [ 96 107 111]
  [ 95 106 110]
  [ 95 106 110]]

 [[ 66  71  77]
  [ 66  71  77]
  [ 67  72  78]
  ...
  [ 95 106 110]
  [ 95 106 110]
  [ 95 106 110]]

 ...

 [[144 122 109]
  [142 124 114]
  [140 125 120]
  ...
  [149 230 251]
  [156 229 248]
  [154 222 241]]

 [[150 119  99]
  [148 120 106]
  [144 124 115]
  ...
  [142 229 246]
  [151 230 245]
  [148 224 238]]

 [[153 117  93]
  [151 118  99]
  [146 122 110]
  ...
  [124 220 234]
  [149 235 248]
  [154 236 247]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[ 66  71  77]
  [ 71  76  82]
  [ 76  81  87]
  ...
  [ 99 110 114]
  [ 98 109 113]
  [ 95 106 110]]

 [[ 67  72  78]
  [ 71  76  82]
  [ 73  78  84]
  ...
  [ 98 109 113]
  [ 99 110 114]
  [ 96 107 111]]

 [[ 70  75  81]

In [3]:
main_list

[array([[[ 66,  71,  77],
         [ 71,  76,  82],
         [ 76,  81,  87],
         ...,
         [ 99, 110, 114],
         [ 98, 109, 113],
         [ 95, 106, 110]],
 
        [[ 67,  72,  78],
         [ 71,  76,  82],
         [ 73,  78,  84],
         ...,
         [ 98, 109, 113],
         [ 99, 110, 114],
         [ 96, 107, 111]],
 
        [[ 70,  75,  81],
         [ 73,  78,  84],
         [ 73,  78,  84],
         ...,
         [ 97, 108, 112],
         [ 99, 110, 114],
         [ 98, 109, 113]],
 
        ...,
 
        [[121, 131, 143],
         [144, 129, 126],
         [145, 129, 130],
         ...,
         [107, 231, 243],
         [ 99, 212, 226],
         [111, 212, 232]],
 
        [[135, 125, 123],
         [138, 132, 136],
         [145, 131, 128],
         ...,
         [ 68, 207, 226],
         [114, 226, 246],
         [153, 228, 249]],
 
        [[148, 120, 106],
         [130, 133, 142],
         [140, 136, 137],
         ...,
         [ 49, 204, 226],
  

In [4]:
pic = 2
for i in range(1,len(fileList)):
    print("PIC NO : ",pic)
    im = Image.open(dirName+"\\"+fileList[i])           
    print("----------X------------X-----------------------X\n\n")
    im.show()
    original_array = np.array(im)
    print(original_array.shape)
    print(original_array.size)
    print(original_array)
    print("\n\n----------X------------X-----------------------X\n\n")
    new_image = im.resize((200, 200))
    resized_array = np.array(new_image)
    print(resized_array.size)
    print(resized_array.shape)
    print(resized_array)
    print("APPENDING TIME")
    main_list.append(resized_array)
    pic = pic+1

PIC NO :  2
----------X------------X-----------------------X


(1000, 1000, 3)
3000000
[[[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]

 [[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]

 [[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]

 ...

 [[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]

 [[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]

 [[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]

 [[255 219 223]
  [255 219 223]
  [255 219 223]
  ...
  [255 219 223]
  [255 219 223]
  [255 219 223]]

 

(225, 225, 3)
151875
[[[ 20  51  45]
  [ 17  48  42]
  [ 13  44  38]
  ...
  [ 22  40  28]
  [ 22  40  26]
  [ 34  40  36]]

 [[ 15  44  39]
  [ 16  45  40]
  [ 16  45  40]
  ...
  [ 32  50  36]
  [ 33  51  37]
  [ 39  46  39]]

 [[ 17  42  36]
  [ 19  44  38]
  [ 22  47  41]
  ...
  [ 38  52  39]
  [ 38  52  37]
  [ 48  53  47]]

 ...

 [[119 114  94]
  [119 114  94]
  [118 113  93]
  ...
  [ 43  53  52]
  [ 50  60  59]
  [ 65  88 120]]

 [[119 114  94]
  [119 114  94]
  [118 113  93]
  ...
  [107 117 116]
  [137 147 146]
  [126 148 208]]

 [[119 117  96]
  [119 117  96]
  [118 116  95]
  ...
  [124 150 199]
  [127 153 212]
  [120 155 213]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[ 20  51  45]
  [ 17  48  42]
  [ 13  44  38]
  ...
  [ 22  40  28]
  [ 22  40  26]
  [ 34  40  36]]

 [[ 15  44  39]
  [ 16  45  40]
  [ 16  45  40]
  ...
  [ 32  50  36]
  [ 33  51  37]
  [ 39  46  39]]

 [[ 17  42  36]
  [ 19  44  38]
  [ 22  47  41]
  ...
  [ 38  52  3

(164, 308, 3)
151536
[[[ 79 114 196]
  [ 79 114 196]
  [ 79 114 196]
  ...
  [ 79 122 201]
  [ 81 124 203]
  [ 82 125 204]]

 [[ 76 112 196]
  [ 76 112 196]
  [ 76 112 196]
  ...
  [ 74 119 200]
  [ 76 121 202]
  [ 77 122 203]]

 [[ 74 112 195]
  [ 74 112 195]
  [ 74 112 195]
  ...
  [ 68 113 196]
  [ 71 116 199]
  [ 72 117 200]]

 ...

 [[ 90 114 174]
  [ 90 114 176]
  [ 91 115 177]
  ...
  [ 83 110 165]
  [ 83 110 165]
  [ 83 110 165]]

 [[ 87 111 171]
  [ 89 113 175]
  [ 92 116 178]
  ...
  [ 80 112 173]
  [ 80 112 173]
  [ 80 112 173]]

 [[ 88 112 172]
  [ 90 114 176]
  [ 93 117 179]
  ...
  [ 75 114 183]
  [ 75 114 183]
  [ 75 114 183]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[ 79 114 196]
  [ 79 114 196]
  [ 79 114 196]
  ...
  [ 77 120 199]
  [ 79 122 201]
  [ 82 125 204]]

 [[ 76 112 196]
  [ 76 112 196]
  [ 76 112 196]
  ...
  [ 72 117 198]
  [ 74 119 200]
  [ 77 122 203]]

 [[ 74 112 195]
  [ 74 112 195]
  [ 74 112 195]
  ...
  [ 66 111 19

(225, 224, 3)
151200
[[[204  78 248]
  [204  78 248]
  [204  78 248]
  ...
  [214  75 255]
  [194  74 247]
  [225 157 244]]

 [[204  78 248]
  [204  78 248]
  [204  78 248]
  ...
  [214  75 255]
  [194  74 247]
  [225 157 244]]

 [[204  78 248]
  [204  78 248]
  [204  78 248]
  ...
  [214  75 255]
  [194  74 247]
  [225 157 244]]

 ...

 [[199  79 239]
  [199  79 239]
  [199  79 239]
  ...
  [211  74 248]
  [191  75 238]
  [222 157 237]]

 [[215  95 252]
  [215  95 252]
  [215  95 252]
  ...
  [227  91 255]
  [207  91 250]
  [237 175 250]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


----------X------------X-----------------------X


120000
(200, 200, 3)
[[[204  78 248]
  [204  78 248]
  [204  78 248]
  ...
  [214  75 255]
  [194  74 247]
  [225 157 244]]

 [[204  78 248]
  [204  78 248]
  [204  78 248]
  ...
  [214  75 255]
  [194  74 247]
  [225 157 244]]

 [[204  78 248]
  [204  78 248]
  [204  78 248]
  ...
  [214  75 25

OSError: cannot identify image file 'photos\\Thumbs.db'

In [ ]:
len(main_list)

In [ ]:
main_list

In [ ]:
main_arr= np.array(main_list)
print("FINAL NUMPY ARRAY :\n\n ",main_arr)

In [ ]:
main_arr.shape

In [ ]:
main_arr.ndim

In [ ]:
main_arr.size